# Generated by Django 5.1.4 on 2025-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureIDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
