# Generated by Django 5.1.4 on 2025-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0002_secureiddata_alter_profile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Story',
            field=models.ImageField(upload_to='StoryIMG/'),
        ),
    ]
