# Generated by Django 5.1.4 on 2025-01-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0003_alter_story_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='Story',
        ),
    ]
