# Generated by Django 5.1.4 on 2025-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0004_remove_story_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
