# Generated by Django 5.1.4 on 2025-01-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0005_story_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='Story',
            field=models.FileField(blank=True, null=True, upload_to='StoryIMG/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
