# Generated by Django 5.1.4 on 2025-01-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0007_imageupload_rename_story_story_storyimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dob', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('Name', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=30)),
                ('Bio', models.TextField()),
                ('Profile_Picture', models.ImageField(upload_to='Profile_Image/')),
            ],
        ),
    ]
