# Generated by Django 5.1.4 on 2025-01-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0008_profilecontainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontainer',
            name='Profile_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_Image/'),
        ),
    ]
