# Generated by Django 5.1.4 on 2025-01-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook', '0009_alter_profilecontainer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecontainer',
            name='Dob',
            field=models.DateTimeField(),
        ),
    ]
